# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a2b1b6c8d471ca60305563dad9beeccac4be91f8fe082fd625baf21e30d7b28152b1e7dd052835c01842e1fcd939a8409eecdbb6630e28badced53431f78eb5

test:
  secret_key_base: a0624ce70198f6c176230a0a577feda3e0962b2c0bf13377cbdfee51559e350d5cc257aaeba335d0d798a602dddbb38de4a268f567cd4b0f80f3b993bdd88b76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
